apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: topolvm-system
  name: topolvm-scheduler
spec:
  template:
    spec:
      containers:
        - name: topolvm-scheduler
          image: topolvm:dev
